# Getting the node image 
FROM node:alpine 

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY frontend-react/package.json .
COPY frontend-react/package-lock.json .
RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g --silent

# add app
COPY ./frontend-react .

# start app
CMD ["npm", "start"]